SUPABASE_URL = "https://esnoapqsjlimfreybokr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbm9hcHFzamxpbWZyZXlib2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NDI1NjMsImV4cCI6MjA4ODQxODU2M30.lYmELOmB5JzGPpXuSMVU4gFmbrd2ix2-8bem-bTaG4U"
GEMINI_API_KEY = "AIzaSyBg4BX_AN26dxI88QIWpL63T6AKVOrLYkU"