SUPABASE_URL = "your_supabase_url_here"
SUPABASE_KEY = "youry_key_here"
GEMINI_API_KEY = "your_api_key_here"

After inserting your real keys in placeholders, rename the "secrets_placeholders.toml" file name to "secrets.toml"
